baseURL: ""
theme: "up-business-theme"
languageCode: "en-us"

title: "PURE DRINKOLOGY"

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
   disableJS: true
   disableHTML: true


googleAnalytics: ""
enableRobotsTXT: false

summaryLength: 20
paginate: 1000
params:
  title: "Drinkology"
  description: "lorem"
  images: 
    - "images/whitelogo.png"

  logo: "blacklogo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    
    
  shareButtons:
     size: small
     icon: solid
     networks:
        - facebook
        - twitter
        - pinterest
        
  copyright: "© 2024 DrawBuildPlay, LLC"
  postProcess: false

  categoryNames:
    cocktail: "Cocktails"
    cafe: "Cafe"
    cocoa: "Cocoa"
    liqueur: "Liqueur"
    nonalcoholic: "Non Alcoholic"
    punch: "Punch"
    shake: "Shake"
    beer: "Beer"
    shot: "Shots"

  categoryOrder:
    - "cocktail"
    - "cafe"
    - "cocoa"
    - "liqueur"
    - "nonalcoholic"
    - "punch"
    - "shake"
    - "beer"
    - "shot"

  familyOrder:
    - "ancestral"
    - "spirit-forward"
    - "negroni"
    - "martini"
    - "sour"
    - "margarita"
    - "highball"
    - "fizz"
    - "other"



menus:
  main:
    - name: "Cocktail Collections"
      url: "/recipes/"
      weight: 2

    - name: "Cocktail Families"
      url: "/recipes/family/"
      weight: 3


    - name: "Spirits"
      url: "/recipes/spirit/"
      weight: 4

    # - name: "Bar Tools"
    #   url: "/tools/"
    #   weight: 4

    # - name: "Getting Started"
    #   url: "/how-to/"
    #   weight: 5

  footer:
    - name: ""
      url: "/"
      weight: 1


permalinks:
  base_spirit: "/recipes/spirit/:slug/"
  family: "/recipes/family/:slug/"
  category: "/recipes/category/:slug/"


taxonomies:
  base_spirit: "base_spirit"
  family: "family"
  category: "category"

related:
  threshold: 0
  toLower: true
  indices:
    - name: "family"
      weight: 100
    - name: "base_spirit"
      weight: 90


