baseURL: ""
theme: "up-business-theme"
languageCode: "en-us"

title: "PURE DRINKOLOGY"

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
   disableJS: true
   disableHTML: true


googleAnalytics: ""
enableRobotsTXT: false

summaryLength: 20
paginate: 1000
params:
  title: "Pure Drinkology"
  description: "Explore a world of cocktail recipes, mixology tips, and bar essentials at Pure Drinkology. From classic to creative cocktails, elevate your home bar experience with our comprehensive guides and vibrant community. Discover, mix, and master the art of the perfect drink."
  images: 
    - "images/logo.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    pinterest: "https://www.pinterest.com/puredrinkology/"
    twitter: "https://www.x.com/puredrinkology/"
    
    
  shareButtons:
     size: small
     icon: solid
     networks:
        - facebook
        - twitter
        - pinterest
        
  copyright: "© 2024 DrawBuildPlay, LLC"
  postProcess: false

  categoryNames:
    cocktail: "Cocktails"

  categoryOrder:
    - "cocktail"
    - "liqueur"
    - "punch"
    - "shake"
    - "beer"
    - "homemade"
    - "shot"

  familyOrder:
    - "ancestral"
    - "spirit-forward"
    - "negroni"
    - "martini"
    - "sour"
    - "margarita"
    - "highball"
    - "fizz"
    - "punch"
    - "creme"
    - "coffee"
    - "chocolate"
    - "refresher"
    - "starbucks"
    - "smoothie"
    - "tea"
    - "other"



menus:
  main:
    - name: "Mocktails"
      url: "/recipes/mocktails/"
      weight: 2

    - name: "Cocktails"
      url: "/recipes/family/"
      weight: 3


    - name: "Spirits"
      url: "/recipes/spirit/"
      weight: 4

    # - name: "Bar Tools"
    #   url: "/tools/"
    #   weight: 4

    # - name: "Getting Started"
    #   url: "/how-to/"
    #   weight: 5

  footer:
    - name: ""
      url: "/"
      weight: 1


permalinks:
  base_spirit: "/recipes/spirit/:slug/"
  family: "/recipes/family/:slug/"
  category: "/recipes/category/:slug/"
  collection: "/recipes/collection/:slug/"


taxonomies:
  base_spirit: "base_spirit"
  family: "family"
  category: "category"
  collection: "collection"

related:
  threshold: 0
  toLower: true
  indices:
    - name: "family"
      weight: 100
    - name: "base_spirit"
      weight: 90


